Add inorganic compounds
manufac-analytics/perry pull request #11
Opened 2021-07-21 19:31 UTC by sumitnegi7

2021-07-21 19:51 UTC, maneetgoyal commented on src/interfaces/utils.ts
> +  value: number | number[];
Revert the change. 

Instead try this:

```ts
export interface PhysicalProperties {
  name: string;
  formula: string;
  formulaWeight: number;
  color?: Qualitative<Colors>[] | Qualitative<Colors>;
  crystallineForms?:
    | Qualitative<CrystallineForms>[]
    | Qualitative<CrystallineForms>;
  refractiveIndex?: Measure | MeasureRange | Measure[];  // CHANGE
  specificGravity?: SpecificGravity;
  meltingOutcomes: MeltingOutcome[];
  boilingOutcomes: MeltingOutcome[];
  solubilitySheet: SolubilitySheet;
}
```

2021-07-24 06:56 UTC, maneetgoyal commented on src/data/inorganic-compounds.ts
> +    specificGravity: {
Ammonia has 2 specific gravities

2021-07-24 07:02 UTC, maneetgoyal commented on src/data/inorganic-compounds.ts
> +        value: 25,
```suggestion
        value: 20,
```

2021-07-24 07:05 UTC, maneetgoyal commented on src/data/inorganic-compounds.ts
> +        nature: SolubilityNature.Soluble, // extra info is 0.005 al (ethylAlcohol95percent)
Quantitative solubility should be used instead

2021-07-24 07:05 UTC, maneetgoyal commented on src/data/inorganic-compounds.ts
> +  AmmoniumTetraChloroplatinate: {
```suggestion
  AmmoniumChloroplatinite: {
```

2021-07-24 07:06 UTC, maneetgoyal commented on src/data/inorganic-compounds.ts
> +    name: 'Ammonium chloroplatinate',
```suggestion
    name: 'Ammonium chloroplatinite',
```

2021-07-24 07:07 UTC, maneetgoyal reviewed
Few corrections, rest LGTM 👍

2021-07-24 07:35 UTC, sumitnegi7 commented
Sir @maneetgoyal  have done the suggested corrections please have a look.

2021-07-24 09:01 UTC, maneetgoyal requested changes

2021-07-24 09:01 UTC, maneetgoyal commented on src/data/inorganic-compounds.ts
> +        formsEntity: '0.005 ethylAlcohol95percent',
Use quanititative solubitiy!!

2021-07-24 09:02 UTC, maneetgoyal commented on src/data/inorganic-compounds.ts
> +        formsEntity: '0.005 ethylAlcohol95percent',
```ts
export interface QuantitativeSolubility {
  value: number | string;
  temperature?: Measure;
  gas: boolean;
}
```

2021-07-24 09:23 UTC, sumitnegi7 commented on src/data/inorganic-compounds.ts
> +        formsEntity: '0.005 ethylAlcohol95percent',
Sorry sir

2021-07-24 09:24 UTC, maneetgoyal approved these changes
LGTM

2021-07-24 09:27 UTC, merged