Migrate vapor pressure data batch2
manufac-analytics/perry pull request #21
Opened 2021-07-26 09:34 UTC by sumitnegi7

2021-07-26 11:49 UTC, qur786 approved these changes
@sumitnegi7 All data is correct

2021-07-27 05:49 UTC, maneetgoyal commented on src/data/vapor-pressure-constants.ts
> +    pressureAtMinimumTemperature: 2.98e1,
```suggestion
    pressureAtMinimumTemperature: 2.98e-1,
```

2021-07-27 05:52 UTC, maneetgoyal commented on src/data/vapor-pressure-constants.ts
> +    pressureAtMinimumTemperature: 6.74e1,
```suggestion
    pressureAtMinimumTemperature: 6.74e-1,
```

2021-07-27 05:53 UTC, maneetgoyal commented on src/data/vapor-pressure-constants.ts
> +    pressureAtMinimumTemperature: 2.93e4,
```suggestion
    pressureAtMinimumTemperature: 2.93e-4,
```

2021-07-27 05:53 UTC, maneetgoyal commented on src/data/vapor-pressure-constants.ts
> +    pressureAtMinimumTemperature: 3.74e7,
```suggestion
    pressureAtMinimumTemperature: 3.74e-7,
```

2021-07-27 05:54 UTC, maneetgoyal commented on src/data/vapor-pressure-constants.ts
> +    pressureAtMinimumTemperature: 2.91e4,
```suggestion
    pressureAtMinimumTemperature: 2.91e-4,
```

2021-07-27 05:54 UTC, maneetgoyal commented on src/data/vapor-pressure-constants.ts
> +    pressureAtMinimumTemperature: 1.24e6,
```suggestion
    pressureAtMinimumTemperature: 1.24e-6,
```

2021-07-27 05:56 UTC, maneetgoyal commented on src/data/vapor-pressure-constants.ts
> +    name: 'trans-2-Butene',
Wrong name

2021-07-27 05:56 UTC, maneetgoyal commented on src/data/vapor-pressure-constants.ts
> +    name: 'trans-2-Butene',
Name

2021-07-27 05:57 UTC, maneetgoyal commented on src/data/vapor-pressure-constants.ts
> +    pressureAtMinimumTemperature: 8.17e2,
```suggestion
    pressureAtMinimumTemperature: 8.17e-2,
```

2021-07-27 05:58 UTC, maneetgoyal requested changes
Corrections needed

2021-07-27 07:13 UTC, maneetgoyal approved these changes

2021-07-27 07:53 UTC, merged