Migrate critical constants and acentric factors batch 2
manufac-analytics/perry pull request #24
Opened 2021-07-27 08:15 UTC by saikat-samanta

2021-07-27 09:39 UTC, qur786 requested changes

2021-07-27 09:39 UTC, qur786 commented on src/data/critical-constants-acentric-factor.ts
> +  Butadiene: {
```suggestion
  Butadiene_1_2: {
```

2021-07-27 16:21 UTC, sumitnegi7 commented on src/data/critical-constants-acentric-factor.ts
> +  trans_2_Butene: {
```suggestion
  trans2Butene: {
```

2021-07-27 16:21 UTC, sumitnegi7 commented on src/data/critical-constants-acentric-factor.ts
> +  cis_2_Butene: {
cis2Butene

2021-07-27 16:22 UTC, maneetgoyal commented on src/data/critical-constants-acentric-factor.ts
> +  Butadiene: {
```suggestion
  '1,2Butadiene': {
```

Don't switch the order of the prefixes.

2021-07-27 16:22 UTC, maneetgoyal commented on src/data/critical-constants-acentric-factor.ts
> +  Butadiene_1_3: {
```suggestion
  '1,3Butadiene': {
```

2021-07-27 16:22 UTC, maneetgoyal commented on src/data/critical-constants-acentric-factor.ts
> +  Butanediol_1_2: {
```suggestion
  '1,2Butanediol': {
```

2021-07-27 16:23 UTC, maneetgoyal commented on src/data/critical-constants-acentric-factor.ts
> +    name: ' 1,2-Butanediol',
```suggestion
    name: '1,2-Butanediol',
```

2021-07-27 16:23 UTC, maneetgoyal commented on src/data/critical-constants-acentric-factor.ts
> +  Butanediol_1_2: {
and so on.

2021-07-28 05:44 UTC, saikat-samanta commented
@manufac-analytics/devs, Requested changes are done 👍

2021-07-28 07:25 UTC, maneetgoyal approved these changes

2021-07-28 18:36 UTC, qur786 approved these changes
all good

2021-07-29 03:54 UTC, merged