migrate critical constants and acentric factors batch 3
manufac-analytics/perry pull request #31
Opened 2021-07-28 06:51 UTC by saikat-samanta

2021-07-28 09:47 UTC, sumitnegi7 commented on src/data/critical-constants-acentric-factor.ts
> +  },
```suggestion
  },
  
```

New lines missing

2021-07-28 10:08 UTC, qur786 requested changes
All data is correct but have some newline and whitespace issues.

2021-07-28 10:08 UTC, qur786 commented on src/data/critical-constants-acentric-factor.ts
> +    name: ' Dimethyl acetylene',
```suggestion
    name: 'Dimethyl acetylene',
```

2021-07-28 10:08 UTC, qur786 commented on src/data/critical-constants-acentric-factor.ts
> +  },
```suggestion
  },
  
```
newline missing , and after this compound as well

2021-07-28 12:31 UTC, qur786 reviewed
All good

2021-07-29 06:22 UTC, qur786 approved these changes

2021-07-29 09:11 UTC, maneetgoyal approved these changes
👍

2021-07-29 10:38 UTC, merged