Migrate critical constants and acentric factors batch 4
manufac-analytics/perry pull request #35
Opened 2021-07-28 13:22 UTC by saikat-samanta

2021-07-29 08:47 UTC, qur786 requested changes

2021-07-29 08:47 UTC, qur786 commented on src/data/critical-constants-acentric-factor.ts
> +  'trans-1,2-Dimethylcyclohexane': {
```suggestion
  'trans1,2Dimethylcyclohexane': {
```

2021-07-30 05:47 UTC, sumitnegi7 commented
@saikat-samanta  can you decrease the batch size from next PR seems pretty big for one PR.

2021-08-02 06:55 UTC, maneetgoyal commented
@manufac-analytics/devs Try to get everything resolved here asap. Been open for a while now.

2021-08-02 10:16 UTC, maneetgoyal approved these changes

2021-08-02 11:54 UTC, qur786 approved these changes

2021-08-02 15:36 UTC, merged