Add compounds to vapor pressure batch10
manufac-analytics/perry pull request #65
Opened 2021-08-06 11:48 UTC by sumitnegi7

2021-08-06 16:21 UTC, saikat-samanta approved these changes
LGTM 👍

2021-08-09 12:17 UTC, qur786 requested changes

2021-08-09 12:17 UTC, qur786 commented on src/data/vapor-pressure-constants.ts
> +    pressureAtMaximumTemperature: 3473000
you can write it , 3.473e6

2021-08-10 05:25 UTC, qur786 approved these changes

2021-08-10 12:35 UTC, merged